import {Map,Marker,NavigationControl,GeolocateControl,addProtocol} from "maplibre-gl";
import "maplibre-gl/dist/maplibre-gl.css"; import "./style.css"; import {searchPlaces,type SearchResult} from "./services/search"; import {aliasPlaces} from "./data/aliases"; import {Protocol} from "pmtiles"; import {makeOfflineStyle} from "./offline-style";
const app=document.querySelector<HTMLDivElement>("#app")!;
app.innerHTML=`<main class="shell"><header><div class="brand"><strong>俄罗斯中文地图</strong><span>RussiaCNMap · 开源预览版</span></div><form id="search"><input id="q" autocomplete="off" placeholder="搜索中文 / 俄文 / 英文，例如：莫航、红场、SVO"/><button>搜索</button></form><div id="results" class="results"></div></header><div id="map"></div><div id="offline-status" class="offline-status">正在读取离线地图…</div><aside id="card" class="card hidden"></aside><footer>中文优先 · 俄文兜底 · 数据源 OpenStreetMap</footer></main>`;
const protocol=new Protocol(); addProtocol("pmtiles",protocol.tile);
const offlineUrl=new URL("moscow.pmtiles",window.location.href).href;
const map=new Map({container:"map",style:makeOfflineStyle(offlineUrl),center:[37.6173,55.7558],zoom:10.8,attributionControl:{}});
map.addControl(new NavigationControl(),"bottom-right"); map.addControl(new GeolocateControl({positionOptions:{enableHighAccuracy:true},trackUserLocation:true}),"bottom-right");
const status=document.querySelector<HTMLDivElement>("#offline-status")!;
map.on("error",e=>{status.textContent="离线地图加载失败";status.classList.add("error");console.error("Map error",e.error);});
map.on("idle",()=>{if(map.areTilesLoaded()){status.textContent="离线地图已加载";status.classList.add("ok");setTimeout(()=>status.classList.add("hidden"),1800);}});
map.on("load",()=>{for(const p of aliasPlaces){const el=document.createElement("div");el.className="offline-label";el.innerHTML=`<b>${p.zh}</b><span>${p.ru}</span>`;new Marker({element:el,anchor:"bottom"}).setLngLat(p.center).addTo(map);}});
let marker:Marker|undefined;
function selectPlace(p:SearchResult){marker?.remove();marker=new Marker({color:"#d63b31"}).setLngLat(p.center).addTo(map);map.flyTo({center:p.center,zoom:15});const card=document.querySelector<HTMLDivElement>("#card")!;card.classList.remove("hidden");card.innerHTML=`<button class="close" aria-label="关闭">×</button><span class="tag">${p.subtitle}</span><h2>${p.zh}</h2><p class="ru">${p.ru}</p><p class="coords">${p.center[1].toFixed(5)}, ${p.center[0].toFixed(5)}</p><small>来源：${p.source==="alias"?"RussiaCNMap 中文别名库":"OpenStreetMap / Nominatim"}</small>`;card.querySelector(".close")?.addEventListener("click",()=>card.classList.add("hidden"));}
const form=document.querySelector<HTMLFormElement>("#search")!,input=document.querySelector<HTMLInputElement>("#q")!,results=document.querySelector<HTMLDivElement>("#results")!;
form.addEventListener("submit",async e=>{e.preventDefault();results.innerHTML='<div class="loading">正在搜索…</div>';const found=await searchPlaces(input.value);results.innerHTML=found.length?found.map((p,i)=>`<button data-i="${i}"><b>${p.zh}</b><span>${p.ru}</span></button>`).join(""):'<div class="loading">没有找到结果</div>';results.querySelectorAll<HTMLButtonElement>("button").forEach(b=>b.addEventListener("click",()=>{selectPlace(found[Number(b.dataset.i)]);results.innerHTML="";}));});
map.on("click",()=>results.innerHTML="");